- name: ensure required paths exist
  file: state=directory path="{{ item }}"
  with_items:
    - /etc/gammu.d

- name: add gammu ppa
  apt_repository:
    repo: 'ppa:nijel/ppa'
    update_cache: yes

- name: install gammu and requirements
  apt: name={{ item }} state=latest
  with_items:
    - gammu
    - gammu-smsd

- name: stop and disable gammu-smsd
  service: name=gammu-smsd state=stopped enabled=no

- name: put gammu smsd conf
  # template: dest=/etc/gammu-smsdrc src=gammu-smsdrc.j2
  template: dest=/etc/gammu.d/gammu-{{ gammu_phoneid }}.conf src={{ gammu_template_name }}
  notify: runit reload gammu-smsd-{{ gammu_phoneid }}
  tags: conf

- name: install gammu-safe
  template: src=gammu-safe.sh dest=/usr/bin/gammu-safe-{{ gammu_phoneid }} mode=755
